version: '3.8'

services:
  postgres-expense:
    image: postgres
    environment:
      POSTGRES_DB: expensedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - fb_postgres_expense_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    networks:
      - fb-net

  redis:
    image: redis/redis-stack-server:latest
    container_name: proselyte-redis_fb
    ports:
      - "6378:6379"
    networks:
      - keycloak_net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: proselyte-redisinsight_fb
    restart: always
    depends_on:
      - redis
    ports:
      - "5539:5540"
    volumes:
      - redis-insight:/data
    networks:
      - keycloak_net

  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: kafka-1_fb
    user: root
    ports:
      - "9092:9092"
    environment:
      - KAFKA_HOSTNAME=${KAFKA_HOSTNAME}
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CLUSTER_ID=ER5TAolPSr2WpjiObebfMA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${KAFKA_HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT #EXTERNAL:SSL in prod
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data-1:/bitnami/kafka
    networks:
      - keycloak_net

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: kafka-2_fb
    user: root
    ports:
      - "9094:9094"
    environment:
      - KAFKA_HOSTNAME=${KAFKA_HOSTNAME}
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CLUSTER_ID=ER5TAolPSr2WpjiObebfMA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${KAFKA_HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT #EXTERNAL:SSL in prod
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data-2:/bitnami/kafka
    networks:
      - keycloak_net

  kafka-3:
    image: 'bitnami/kafka:latest'
    container_name: kafka-3_fb
    user: root
    ports:
      - "9096:9096"
    environment:
      - KAFKA_HOSTNAME=${KAFKA_HOSTNAME}
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CLUSTER_ID=ER5TAolPSr2WpjiObebfMA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${KAFKA_HOSTNAME:-localhost}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT #EXTERNAL:SSL in prod
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data-3:/bitnami/kafka
    networks:
      - keycloak_net



  #KEYCLOAK

  postgres:
    image: postgres
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloakrealm
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    #    image: quay.io/keycloak/keycloak
    container_name: keycloak
    #    command: start-dev
    build:
      context: .
      dockerfile: Dockerfile.keycloak

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9094
      KAFKA_TOPIC: session-events
      REALM_NAME: family_budget
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_net



networks:
  fb-net:
    driver: bridge
  proselyte-redis-net:
    driver: bridge
  keycloak_net:
    driver: bridge

volumes:
  fb_postgres_expense_data:
  redis-insight:
  kafka_data-1:
  kafka_data-2:
  kafka_data-3:
  postgres_data:






