services:
  postgres-user:
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - fb_postgres_user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fb-net


  postgres-expense:
    image: postgres
    environment:
      POSTGRES_DB: expensedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - fb_postgres_expense_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - fb-net


  postgres-auth:
    image: postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - fb_postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - fb-net

networks:
  fb-net:
    driver: bridge