version: '3.8'

services:
  postgres:
    image: postgres
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloakrealm
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
#    image: quay.io/keycloak/keycloak
    container_name: keycloak
#    command: start-dev
    build:
      context: .
      dockerfile: Dockerfile.keycloak

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      REDIS_HOST: redis
      REDIS_PORT: 6378
#      KAFKA_BOOTSTRAP_SERVERS: localhost:9092,localhost:9094
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9090,kafka-2:9090,kafka-3:9090
      KAFKA_TOPIC: session-events
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_net

volumes:
  postgres_data:

networks:
  keycloak_net:
    driver: bridge