server:
  port: 9000
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator: true


  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/family_budget"
          jwk-set-uri: "http://localhost:9090/realms/family_budget/protocol/openid-connect/certs"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
