server:
  port: 8080
spring:
  application:
    name: expense-service
  profiles:
    active: docker # или dev, если хочешь локально с H2
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
